### ISSUE TITLE
RFE: Adapt a version for ReviewMeta

### ISSUE THREAD

**Issue by TPS** [cstew/TryCamel#2]
Would you consider a version of this app that sends this to https://reviewmeta.com/ ?  It seems very little might need to be changed, but would be as useful as this original app.

Your MIT license does allow _others_ to do this,  but I think any improvements you make to either app would simply directly help the other if you did both yourself.

**Comment by cstew** [comment]
I'm not interested in doing that for this project. Feel free to fork.
