### ISSUE TITLE
Allow F-Droid flavor for RFP

### ISSUE THREAD

**Issue by TPS** [cstew/TryCamel#3]
This app seems like it might be a prime candidate to include in F-Droid, but per https://f-droid.org/en/docs/Inclusion_Policy/ , it shouldn't include proprietary libraries.  According to https://reports.exodus-privacy.eu.org/en/reports/63968/ the app uses Google's Crashlytics, which is specifically prohibited.

So, this issue is to comply w/ the requirements from https://f-droid.org/en/docs/Inclusion_How-To/ :
- [ ] Your (@cstew's) permission to work toward F-Droid inclusion (for this app & perhaps the version proposed in #2)
- [ ] Your interest in removal/replacement of any showstoppers for that

@IzzySoft Did I forget anything?

**Comment by IzzySoft** [comment]
It would help if releases were [tagged](https://github.com/cstew/TryCamel/releases), so new versions can be auto-detected. If there's more, we'll see that after an RFP has been filed and the bot has checked :wink:

**Comment by cstew** [comment]
Not interested. Thanks.
